language: node_js
node_js:
  - 8
  - 10
cache:
  yarn: true
  directories:
    - node_modules
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - yarn global add yarn@1
  - yarn global add greenkeeper-lockfile@2
  - chmod +x -R ./scripts
install: ./scripts/install_all.sh
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - ./scripts/ci_all.sh
